security:
  oauth2:
    client:
      # For client id and secret, refer to:
      # https://www.strava.com/settings/api
      # Instead of setting here, see README.md to set as command line arguments
      client-id: 
      client-secret: 
      access-token-uri: https://www.strava.com/oauth/token
      user-authorization-uri: https://www.strava.com/oauth/authorize
      scope: view_private
      token-name: access_token
      authentication-scheme: query
      client-authentication-scheme: form
    resource:
      user-info-uri: https://www.strava.com/api/v3/athlete

spring:
  datasource:
    url: jdbc:h2:file:~/stravadb        
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    hibernate:
      ddl-auto: update
  # enable H2 web console and set url for web console
  # http://localhost:8080/console
  h2:
    console:
      enabled: true
      path: /console